version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: pyro-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pyro_postgres_data:/var/lib/postgresql/data

volumes:
  pyro_postgres_data:
